### ISSUE TITLE
angular modules 404

### ISSUE THREAD

**Issue by nordbit** [rodrigobraga/informer#2]
Few words about installing angular modules? Or list of modules at least?

**Comment by rodrigobraga** [comment]
@nordbit The files from AngularJS goes with package (wheel), to use in development, you need run "npm install" on folder that have the package.json file.

**Comment by nordbit** [comment]
OK, thx for explanation and good luck.

**Comment by rodrigobraga** [comment]
OK @nordbit.

Did you have any issue with this?
